export const matches = [
  {
    id: 1,
    sport: "Tennis",
    location: "Maryland Heights Tennis Center",
    date: "September 10, 2026",
    time: "6:00 PM",
    skillLevel: "Intermediate",
    currentPlayers: 2,
    maxPlayers: 4,
    organizer: "Alex",
  },
  {
    id: 2,
    sport: "Pickleball",
    location: "O'Fallon Community Center",
    date: "September 11, 2026",
    time: "5:30 PM",
    skillLevel: "Beginner",
    currentPlayers: 3,
    maxPlayers: 4,
    organizer: "Maya",
  },
  {
    id: 3,
    sport: "Basketball",
    location: "St. Peters Rec-Plex",
    date: "September 12, 2026",
    time: "7:00 PM",
    skillLevel: "Intermediate",
    currentPlayers: 4,
    maxPlayers: 10,
    organizer: "Jordan",
  },
  {
    id: 4,
    sport: "Tennis",
    location: "Creve Coeur Park Tennis Courts",
    date: "September 13, 2026",
    time: "6:30 PM",
    skillLevel: "Advanced",
    currentPlayers: 1,
    maxPlayers: 2,
    organizer: "Chris",
  },
  {
    id: 5,
    sport: "Pickleball",
    location: "Chesterfield Valley Athletic Complex",
    date: "September 14, 2026",
    time: "9:00 AM",
    skillLevel: "Intermediate",
    currentPlayers: 2,
    maxPlayers: 4,
    organizer: "Taylor",
  },
  {
    id: 6,
    sport: "Soccer",
    location: "Soccer Park at the Maryland Heights",
    date: "September 15, 2026",
    time: "10:00 AM",
    skillLevel: "Intermediate",
    currentPlayers: 6,
    maxPlayers: 14,
    organizer: "Sam",
  },
  {
    id: 7,
    sport: "Volleyball",
    location: "Vetta Sports Center",
    date: "September 15, 2026",
    time: "5:00 PM",
    skillLevel: "Beginner",
    currentPlayers: 5,
    maxPlayers: 10,
    organizer: "Emily",
  },
  {
    id: 8,
    sport: "Tennis",
    location: "St. Charles Tennis Center",
    date: "September 16, 2026",
    time: "8:00 AM",
    skillLevel: "Beginner",
    currentPlayers: 1,
    maxPlayers: 2,
    organizer: "Daniel",
  },
  {
    id: 9,
    sport: "Basketball",
    location: "Queeny Park Recreation Complex",
    date: "September 16, 2026",
    time: "6:00 PM",
    skillLevel: "Advanced",
    currentPlayers: 3,
    maxPlayers: 10,
    organizer: "Marcus",
  },
  {
    id: 10,
    sport: "Pickleball",
    location: "Kirkwood Community Center",
    date: "September 17, 2026",
    time: "7:30 PM",
    skillLevel: "Beginner",
    currentPlayers: 2,
    maxPlayers: 4,
    organizer: "Sophia",
  },
  {
    id: 11,
    sport: "Soccer",
    location: "Francis Slay Park",
    date: "September 18, 2026",
    time: "6:30 PM",
    skillLevel: "Advanced",
    currentPlayers: 7,
    maxPlayers: 14,
    organizer: "Ryan",
  },
  {
    id: 12,
    sport: "Volleyball",
    location: "Brentwood Community Center",
    date: "August 18, 2026",
    time: "7:00 PM",
    skillLevel: "Intermediate",
    currentPlayers: 4,
    maxPlayers: 10,
    organizer: "Olivia",
  },
  {
    id: 13,
    sport: "Tennis",
    location: "Tower Grove Park Tennis Courts",
    date: "September 19, 2026",
    time: "5:30 PM",
    skillLevel: "Intermediate",
    currentPlayers: 1,
    maxPlayers: 2,
    organizer: "Noah",
  },
  {
    id: 14,
    sport: "Basketball",
    location: "Florissant Valley Recreation Center",
    date: "September 20, 2026",
    time: "7:30 PM",
    skillLevel: "Beginner",
    currentPlayers: 5,
    maxPlayers: 10,
    organizer: "Ethan",
  },
  {
    id: 15,
    sport: "Pickleball",
    location: "Clayton Community Center",
    date: "August 21, 2026",
    time: "6:00 PM",
    skillLevel: "Advanced",
    currentPlayers: 1,
    maxPlayers: 4,
    organizer: "Ava",
  },
  {
    id: 16,
    sport: "Soccer",
    location: "Lafayette Park",
    date: "August 21, 2026",
    time: "5:00 PM",
    skillLevel: "Beginner",
    currentPlayers: 8,
    maxPlayers: 14,
    organizer: "Liam",
  },
  {
    id: 17,
    sport: "Tennis",
    location: "Frontenac Racquet Club",
    date: "August 22, 2026",
    time: "9:30 AM",
    skillLevel: "Advanced",
    currentPlayers: 1,
    maxPlayers: 2,
    organizer: "Isabella",
  },
  {
    id: 18,
    sport: "Volleyball",
    location: "Maryland Heights Community Center",
    date: "August 22, 2026",
    time: "4:30 PM",
    skillLevel: "Intermediate",
    currentPlayers: 3,
    maxPlayers: 10,
    organizer: "Lucas",
  },
  {
    id: 19,
    sport: "Basketball",
    location: "O'Fallon Sports Park",
    date: "August 23, 2026",
    time: "3:00 PM",
    skillLevel: "Intermediate",
    currentPlayers: 6,
    maxPlayers: 10,
    organizer: "James",
  },
  {
    id: 20,
    sport: "Pickleball",
    location: "St. Louis County Recreation Center",
    date: "August 23, 2026",
    time: "10:00 AM",
    skillLevel: "Beginner",
    currentPlayers: 2,
    maxPlayers: 4,
    organizer: "Emma",
  },
];
